---
- name: root | stat to check whether /root/.my.cnf exists
  stat:
    path: /root/.my.cnf
  register: cnf_file

- block:

    - name: root | place temporary cnf file
      template:
        src: temp_cnf.j2
        dest: /etc/my.cnf
        mode: '0644'

    - name: root | start mysql
      systemd:
        name: mysql
        state: started
        enabled: true

    - name: root | get temp root password
      shell: >-
        grep 'temporary password' /var/log/mysqld.log |
        awk '{print $NF}' | tail -n 1
      register: temp_root_pw
      no_log: "{{ percona_no_log }}"

    - name: root | set root password
      shell: >-
        mysqladmin -u root
        --password="{{ temp_root_pw.stdout }}"
        password "{{ percona_root_password }}"
      no_log: "{{ percona_no_log }}"

    - name: root | set debian-sys-maint user and password
      mysql_user:
        name: debian-sys-maint
        password: "{{ percona_system_password }}"
        priv: '*.*:ALL,GRANT'
        update_password: always
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock
        login_user: root
        login_password: "{{ percona_root_password }}"
      no_log: "{{ percona_no_log }}"

    - name: root | copy root.cnf
      template:
        src: root.cnf.j2
        dest: /etc/mysql/root.cnf
        mode: '0660'
        owner: mysql
        group: root

    - name: root | symlink /etc/mysql/root.cnf to /root/.my.cnf
      file:
        state: link
        src: /etc/mysql/root.cnf
        path: /root/.my.cnf

    - name: root | delete anonymous connections
      mysql_user:
        name: ""
        host_all: true
        state: absent
      no_log: "{{ percona_no_log }}"

    - name: root | secure root user
      mysql_user:
        name: root
        host: "{{ item }}"
      no_log: "{{ percona_no_log }}"
      loop:
        - ::1
        - 127.0.0.1
        - localhost

    - name: root | ensure test database is removed
      mysql_db:
        name: test
        login_user: root
        state: absent

    - name: root | stop mysql
      systemd:
        name: mysql
        state: stopped
        enabled: true

    - name: root | remove mysqld log file
      file:
        path: /var/log/mysqld.log
        state: absent

  when: not cnf_file.stat.exists
